### ISSUE TITLE
Import della libreria Arduino

### ISSUE THREAD

**Issue by dariosortino** [michele-bertoni/ViRHaS#1]
Ciao michele,
sto provando a importare la libreria tramite "Import from Zip" in arduino ma non è possibile importare tale libreria. Potresti darmi una mano?

**Comment by michele-bertoni** [comment]
Immagino che tu abbia scaricato lo zip intero da Github. Estrailo, poi prendi le 3 cartelle all'interno di ViRHaS_ino/libraries e copiale manualmente all'interno della directory delle librerie del tuo arduino ide. Dovrebbe essere in Documents/Arduino/libraries

**Comment by dariosortino** [comment]
Mi complicavo la vita inutilmente, grazie, ora importa correttamente. Scusa se continuo a disturbarti ma sei l'unico che può darmi una mano celermente.

Hai idea di come potrei risolvere

`no matching function for call to 'ViRHaS::ViRHaS(CytronMD&, CytronMD&, CytronMD&, Encoder&, Encoder&, Encoder&)'`

quando chiamo 

`ViRHaS virhas = ViRHaS(motor1, motor2, motor3, ENCODER[0], ENCODER[1], ENCODER[2]);`

Gli argomenti passati sono della classe corretta

**Comment by michele-bertoni** [comment]
Il prototipo del costruttore è questo: 
`ViRHaS(MR001004 & m1m2, MR001004 & m3, Encoder & e1, Encoder & e2, Encoder & e3);`
La libreria è fatta per funzionare con i driver MR001004, quindi se vuoi usarla devi modificarla leggermente

**Comment by dariosortino** [comment]
Grazie mille, risolverò modificando direttamente la libreria. Ti auguro una buona serata. Ciao!

**Comment by michele-bertoni** [comment]
Grazie, buon lavoro!
